# Imports

In [1]:
import sys
import os
import joblib
from pathlib import Path

In [2]:
sys.path.append(os.path.join(os.getcwd(),"..",".."))

In [3]:
import numpy as np
import pandas as pd

In [4]:
from computing_factors import Compute_Factors

In [5]:
data_store=Path(os.getcwd()).parent.parent/"Prepared_Data_Store"

# Load Models

In [6]:
ridge18=joblib.load(os.path.join(data_store,"ridge_18.pkl"))
ridge17=joblib.load(os.path.join(data_store,"ridge_17.pkl"))
ridge16=joblib.load(os.path.join(data_store,"ridge_16.pkl"))
ridge15=joblib.load(os.path.join(data_store,"ridge_15.pkl"))
ridge14=joblib.load(os.path.join(data_store,"ridge_14.pkl"))

In [7]:
models=[
    ridge18,
    ridge17,
    ridge16,
    ridge15,
    ridge14,
    
]

In [8]:
model_names=[
    "Ridge18",
    "Ridge17",
    "Ridge16",
    "Ridge15",
    "Ridge14",
    
]

# Load Features Data

In [9]:
train_X=pd.read_csv(
    os.path.join(data_store,"model1_train_X.csv"),
    parse_dates=["date"],
    index_col=["date","ticker"]
)

In [10]:
test_X=pd.read_csv(
    os.path.join(data_store,"model1_test_X.csv"),
    parse_dates=["date"],
    index_col=["date","ticker"]
)

In [11]:
feature_data=pd.concat([train_X,test_X],axis=0).sort_index()

In [12]:
feature_data

                       open      high       low     close    volume  \
date       ticker
2010-02-22 A      -1.571355 -1.621298 -1.566455 -1.588083 -0.156541
           ACGL   -1.576142 -1.574122 -1.564216 -1.568240  3.054903
           ACN    -1.503369 -1.518475 -1.506436 -1.519097 -0.338131
           ADI    -1.462160 -1.479389 -1.463275 -1.469124  0.904611
           ADM    -0.916182 -0.923291 -0.902353 -0.917975 -0.511968
...                     ...       ...       ...       ...       ...
2017-11-29 XEL     4.955182  4.924600  4.978221  4.959050 -0.398981
           XOM     0.865560  0.875673  0.900603  0.919322 -0.877773
           YUM     3.971184  3.987502  4.033490  4.025041 -0.912763
           ZBH     1.796875  1.809269  1.816320  1.842295  0.281990
           ZBRA    2.650407  2.625413  2.579282  2.551066 -0.012507

                   dollar_volume  dollar_volume_7d  dollar_volume_15d  \
date       ticker
2010-02-22 A           -0.693067         -0.279116          -0.341175
           ACGL         1.343749          1.911222           1.708494
           ACN         -0.758531         -0.957332          -0.950981
           ADI         -0.044209          1.348163           0.612157
           ADM         -0.916221         -0.615638           0.118269
...                          ...               ...                ...
2017-11-29 XEL          1.118258          1.086837           2.238832
           XOM         -0.859138         -1.572008          -1.633973
           YUM         -0.224668         -0.750260          -0.606211
           ZBH          1.635718          0.293123           0.685519
           ZBRA         0.628077          0.283488           1.051882

                   dollar_volume_21d  dollar_volume_rank  ...  max_price_7d  \
date       ticker                                         ...
2010-02-22 A               -0.708899            0.014026  ...     -1.698506
           ACGL             1.505118           -2.431023  ...     -1.574045
           ACN             -0.963062            1.277944  ...     -1.529100
           ADI              0.524131           -1.456467  ...     -1.513738
           ADM              0.143165           -0.951449  ...     -0.967399
...                              ...                 ...  ...           ...
2017-11-29 XEL              2.692266           -1.705930  ...      4.827169
           XOM             -1.751713            6.946481  ...      0.820971
           YUM             -0.305037            2.145209  ...      3.852468
           ZBH              2.767348           -0.921958  ...      1.768455
           ZBRA             1.096640            0.340392  ...      2.419100

                   max_price_15d  max_price_21d       rsi  bb_lower  bb_upper  \
date       ticker
2010-02-22 A           -1.765908      -1.805616  1.054291  0.995363 -0.970205
           ACGL        -1.577768      -1.577905  0.378266  0.452331 -0.631467
           ACN         -1.536885      -1.526227 -1.015514 -0.732887 -0.034553
           ADI         -1.533649      -1.541487  0.919647  2.052763 -1.320108
           ADM         -0.862954      -0.888895 -0.538155 -0.582187 -0.188531
...                          ...            ...       ...       ...       ...
2017-11-29 XEL          4.848009       4.807799  1.104867  0.378248 -0.452060
           XOM          0.916336       0.884109  0.088974 -0.231193 -0.103991
           YUM          3.737471       3.676053  1.458015  0.750441 -0.794452
           ZBH          1.727168       1.934896  0.366639  0.964875 -0.663773
           ZBRA         2.324706       2.549186 -0.181772  0.122770  0.224838

                   avg_true_range      macd  macd_hist  macd_signal
date       ticker
2010-02-22 A            -1.349682 -0.033359   1.557912    -0.533920
           ACGL         -1.290628 -0.300647   0.758958    -0.574566
           ACN          -1.238902 -0.966192   0.624403    -1.302019
           ADI          -0.664605 -0.528868   2.527034    -1.443055
           ADM          -0.670952 -0.382994   0.135996    -0.453226
...                           ...       ...        ...          ...
2017-11-29 XEL           1.326506  1.907064  -0.178037     2.148384
           XOM          -1.227057 -0.465833  -0.225180    -0.421524
           YUM           0.652513  1.544597   0.726822     1.403071
           ZBH           1.357875 -0.831866   1.931008    -1.571614
           ZBRA          1.594293 -0.280305   0.394581    -0.407737

[732292 rows x 76 columns]

# Factor Computation

In [13]:
factor_computer=Compute_Factors(
    models=models,
    model_names=model_names,
    feature_data=feature_data
)

In [14]:
factors=factor_computer.compute_factors()

[INFO] Factor Computation started...



[INFO] Ridge18 Factors computed...
[INFO] Ridge17 Factors computed...
[INFO] Ridge16 Factors computed...
[INFO] Ridge15 Factors computed...
[INFO] Ridge14 Factors computed...
[INFO] Combined Factors computed...



[INFO] Factor Computation completed...

In [15]:
factors

                   Ridge18_factor  Ridge17_factor  Ridge16_factor  \
date       ticker
2010-02-22 A             0.002118        0.002676        0.002893
           ACGL          0.001241        0.002445        0.003014
           ACN           0.001982        0.003217        0.003933
           ADI           0.000734        0.003731        0.005258
           ADM          -0.000516       -0.000472       -0.000061
...                           ...             ...             ...
2017-11-29 XEL          -0.002817       -0.004791       -0.005825
           XOM          -0.000058       -0.001477       -0.002078
           YUM          -0.001453       -0.001177       -0.001173
           ZBH          -0.000151        0.001043        0.000991
           ZBRA         -0.001567       -0.001123       -0.001045

                   Ridge15_factor  Ridge14_factor  Combined_factors
date       ticker
2010-02-22 A             0.003206        0.003132          0.002805
           ACGL          0.003444        0.003208          0.002670
           ACN           0.005214        0.005427          0.003955
           ADI           0.007284        0.007306          0.004862
           ADM           0.001719        0.002456          0.000625
...                           ...             ...               ...
2017-11-29 XEL          -0.007491       -0.007738         -0.005732
           XOM          -0.003008       -0.003125         -0.001949
           YUM          -0.002016       -0.002484         -0.001661
           ZBH           0.000426        0.000683          0.000598
           ZBRA         -0.001144       -0.001216         -0.001219

[732292 rows x 6 columns]

# Saving Factor Data

In [16]:
factors.to_csv(os.path.join(data_store,"ridge_factors.csv"),index=True)